# Adding Average Route Time (actual_elapsed_time) + Avg Dep/Arr delay

In [47]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import sklearn.preprocessing

In [48]:
my_path = 'C:/Users/user/lighthouse/Midterm_Project/Predicting_Flight_Delays/workbench/'
df = pd.read_csv(my_path +'feature_2.csv')
df.head()

,Unnamed: 0,origin,dest,taxi_out,taxi_in,month,day_of_week,carrier_encoded,haul_encoded,binned_dep,binned_arr,binned_distance,route,average_route_time,arr_delay
0,0,46,297,20.0,4.0,5,4,3,2,5,6,1,672,125.024174,-14.0
1,1,21,290,12.0,2.0,7,6,3,2,8,8,1,255,125.024174,-14.0
2,2,21,83,34.0,3.0,3,5,3,2,4,4,1,167,125.024174,13.0
3,3,184,320,22.0,8.0,9,0,3,1,3,4,2,2941,125.024174,-18.0
4,4,86,240,25.0,2.0,8,2,3,2,6,6,1,1249,125.024174,11.0

In [49]:
new_path = "C:/Users/user/lighthouse/Midterm_Project/Predicting_Flight_Delays/workbench/"
df2 = pd.read_csv(new_path +'flights_unscaled.csv')
df2.head()

,origin,dest,crs_dep_time,crs_arr_time,arr_delay,crs_elapsed_time,air_time,distance,carrier,month,day_of_week,mean_hist_dep_delay,mean_hist_arr_delay
0,46,297,14,16,-14.0,114.0,78.0,474.0,3,5,4,7.857507,1.722365
1,73,308,16,18,19.0,192.0,171.0,1095.0,2,12,4,9.247318,4.573334
2,21,290,21,23,-14.0,161.0,133.0,1027.0,3,7,6,10.701001,4.330997
3,271,44,20,23,-14.0,129.0,101.0,735.0,2,4,0,11.688123,4.330997
4,193,92,16,19,-17.0,112.0,82.0,628.0,9,12,3,9.247318,5.387877

In [51]:
df3 = pd.merge(df,df2,how='inner')
df3 = df3.drop(['Unnamed: 0', 'crs_dep_time', 'crs_arr_time','air_time','distance', 'carrier', 'crs_elapsed_time'], axis=1)

In [52]:
df3.head()

,origin,dest,taxi_out,taxi_in,month,day_of_week,carrier_encoded,haul_encoded,binned_dep,binned_arr,binned_distance,route,average_route_time,arr_delay,mean_hist_dep_delay,mean_hist_arr_delay
0,46,297,20.0,4.0,5,4,3,2,5,6,1,672,125.024174,-14.0,7.857507,1.722365
1,21,290,12.0,2.0,7,6,3,2,8,8,1,255,125.024174,-14.0,10.701001,4.330997
2,21,83,34.0,3.0,3,5,3,2,4,4,1,167,125.024174,13.0,4.143817,-3.180434
3,184,320,22.0,8.0,9,0,3,1,3,4,2,2941,125.024174,-18.0,0.845592,-3.180434
4,86,240,25.0,2.0,8,2,3,2,6,6,1,1249,125.024174,11.0,8.389935,1.722365

In [53]:
df3.to_csv('feature_3.csv')